### ISSUE TITLE
您好，请教一个问题。

### ISSUE THREAD

**Issue by ZQiang94** [JackyAndroid/AndroidInterview-Q-A#10]
相同功能的一个页面，例如登录页面。使用Fragment与Activity在性能上有什么显著的差异么？项目中新开一个Activity的内存开销是怎样的呢？我认为两种方式实现，内存开销的差异上并不是很大，是这样么？期待您的回复，谢谢。

**Comment by JackyAndroid** [comment]
这两种创建页面的方式开销差别不大，activity稍重一些，但是基本用户无感知。可以看看activity和fragment的创建过程
