### ISSUE TITLE
不会调用draw()过程，但不会重新绘制 任何视图包括该调用者本身。

### ISSUE THREAD

**Issue by Tryking** [JackyAndroid/AndroidInterview-Q-A#16]
Requestlayout,onlayout,onDraw,DrawChild区别与联系-猎豹

requestLayout()方法 ：会导致调用measure()过程 和 layout()过程 。 说明：只是对View树重新布局layout过程包括measure()和layout()过程，不会调用draw()过程，但不会重新绘制 任何视图包括该调用者本身。

这句话有错吧？“不会调用draw()过程” 这句应该是会调用draw过程吧？

**Comment by JackyAndroid** [comment]
@Tryking 应该是会根据绘制标志位判断是否绘制，多谢指正
