### ISSUE TITLE
[建议]是否考虑整理为gitbook?

### ISSUE THREAD

**Issue by didikee** [JackyAndroid/AndroidInterview-Q-A#20]
起因:因为手机查看md的限制,和移动端查看网页在地铁等情形下体验不好.

有没有考虑把这些文章整理为在 gitbook 上,gitbook 目前支持下载为pdf,这在给去面试路上(公交or地铁)的同学极大的便利,恰巧坐车也很无聊,不如利用起来温故下.

**Comment by JackyAndroid** [comment]
@didikee gitbook：http://www.jackywang.tech/AndroidInterview-Q-A/。目前大概整理了下，部分内容还没有添加，如果有时间可以提交PR，想要pdf可以更新下项目使用命令生成

**Comment by JackyAndroid** [comment]
@didikee 已经全部转为Gitbook
