### ISSUE TITLE
404

### ISSUE THREAD

**Issue by yangkun19921001** [JackyAndroid/AndroidInterview-Q-A#39]
在线文档 404 了。
![image](https://user-images.githubusercontent.com/20500834/76282869-0da92880-62d4-11ea-8a2b-cda58a44f5e2.png)

**Comment by JackyAndroid** [comment]
正在解决

**Comment by JackyAndroid** [comment]
先使用境外站点：https://jackyandroid.github.io/AndroidInterview-Q-A/

**Comment by yangkun19921001** [comment]
好的，谢谢！

**Comment by brandonstack** [comment]
还是404

**Comment by JackyAndroid** [comment]
@brandonstack 再试下，我这边用的chrome桌面版

**Comment by JackyAndroid** [comment]
@all 记得清理下浏览器缓存

**Comment by Mccreeeee** [comment]
还是404，清理缓存没有作用

**Comment by 0924chun** [comment]
404啊

**Comment by JackyAndroid** [comment]
再试下，确认地址是https://jackyandroid.github.io/AndroidInterview-Q-A/，如果定向到其他地址清缓存或者换下浏览器

**Comment by 0924chun** [comment]
可以了 谢谢

**Comment by CodeIdeal** [comment]
又404了

**Comment by JackyAndroid** [comment]
已部署到腾讯云，大家可以试试。
https://interview-q-a-1gdnkgkla15afdbe-1258598664.tcloudbaseapp.com/
